version: "3.7"
services:
  nginx:
    container_name: debate_server
    image: nginx:1.15
    volumes:
      - ./:/var/www
      - ./server_config/debate_nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 15101:80
    networks:
      - debate-network
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: debate_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: "npm run start:prod"
    tty: true
    volumes:
      - appdata:/app
    networks:
      debate-network:
        aliases:
          - frontend

  backend:
    container_name: debate_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5500 app:app
    environment:
      SECRET_KEY: prdDebateSecret
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: "debate_manager"
      MONGODB_PASSWORD: "manPrd4892#"
    volumes:
      - appdata:/var/www/
    depends_on:
      - mongodb
    networks:
      debate-network:
        aliases:
          - backend

  mongodb:
    container_name: debate_db
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "prd_debate_admin"
      MONGO_INITDB_ROOT_PASSWORD: "debate2140"
      TARGET_DATABASE: "debate_web"
      TARGET_USERNAME: "debate_manager"
      TARGET_PASSWORD: "manPrd4892#"
      MONGODB_DATA_DIR: mongodbdata
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - 27017:27017
    networks:
      debate-network:
        aliases:
          - mongodb

networks:
  debate-network:
volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
