version: "3.7"
services:
  nginx:
    container_name: debate_server
    image: nginx:1.15
    volumes:
      - ./:/var/www
      - ./server_config/debate_nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 15101:80
    networks:
      - debate-network
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: debate_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "13102:3300"
    volumes:
      - appdata:/app
    networks:
      debate-network:
        aliases:
          - frontend

  backend:
    container_name: debate_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5500 app:app
    ports:
      - 5500:5500
    environment:
      MONGODB_HOST: debate_web
      MONGODB_USERNAME: "debate_manager"
      MONGODB_PASSWORD: "manPrd4892#"
    volumes:
      - appdata:/var/www/
    depends_on:
      - mongodb
    networks:
      debate-network:
        aliases:
          - backend

  mongodb:
    container_name: debate_db
    build:
      context: ./db
      dockerfile: Dockerfile
    image: mongo
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGODB_DATA_DIR: mongodbdata
    volumes:
      - mongodbdata:/data/db
      - mongodbdata:/data/configdb
    ports:
      - 27017:27017
    networks:
      debate-network:
        aliases:
          - mongodb

networks:
  debate-network:
volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
