version: "3.7"
services:
  nginx:
    container_name: debate_server
    image: dreamx119/debate_server
    build:
      context: ../server_config
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - debate-network
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: debate_frontend
    image: dreamx119/debate_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: "npm run start"
    tty: true
    networks:
      debate-network:

  backend:
    container_name: debate_backend
    image: dreamx119/debate_backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5500 wsgi:app
    environment:
      SECRET_KEY: prdDebateSecret
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: "debate_manager"
      MONGODB_PASSWORD: "manPrd4892#"
      DEBATE_INIT_USER_PWD: "debateAdmin"
    depends_on:
      - mongodb
    networks:
      debate-network:

  mongodb:
    container_name: debate_db
    image: dreamx119/debate_db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - mongodbdata:/docker-entrypoint-initdb.d/
      - mongodbdata:/data/configdb/
      - mongodbdata:/data/db/
    networks:
      debate-network:

networks:
  debate-network:
volumes:
  mongodbdata:
    driver: local
