version: "3.7"
services:
  nginx:
    container_name: debate_server
    image: dreamx119/debate_server
    ports:
      - 80:80
      - 443:443
    networks:
      - debate-network
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: debate_frontend
    image: dreamx119/debate_frontend
    tty: true
    networks:
      debate-network:

  backend:
    container_name: debate_backend
    image: dreamx119/debate_backend
    environment:
      SECRET_KEY: prdDebateSecret
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: "debate_manager"
      MONGODB_PASSWORD: "manPrd4892#"
      DEBATE_INIT_USER_PWD: "debateAdmin"
    depends_on:
      - mongodb
    networks:
      debate-network:

  mongodb:
    container_name: debate_db
    image: dreamx119/debate_db
    restart: unless-stopped
    volumes:
      - mongodbdata:/docker-entrypoint-initdb.d/
      - mongodbdata:/data/configdb/
      - mongodbdata:/data/db/
    networks:
      debate-network:

networks:
  debate-network:
volumes:
  mongodbdata:
    driver: local
