apiVersion: apps/v1
kind: Deployment
metadata:
  name: debate_frontend-deployment
spec:
  selector:
    matchLabels:
      app: debate_frontend
  template:
    metadata:
      labels:
        app: debate_frontend
    spec:
      containers:
        - name: debate_frontend
          image: dreamx119/debate_frontend
