apiVersion: apps/v1
kind: Deployment
metadata:
  name: debate_server-deployment
spec:
  selector:
    matchLabels:
      app: debate_server
  replicas: 2
  template:
    metadata:
      labels:
        app: debate_server
    spec:
      containers:
        - name: debate_server
          image: dreamx119/debate_server
          ports:
            - containerPort: 80
