name: debate_app

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  frontend_build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          cd frontend
          npm ci
          npm run build --if-present

  backend_build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: python app build
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install setuptools wheel twine
          python setup.py build
          python setup.py install
