name: debate_pre_builder

# Trigger settings
on:
  pull_request:
    branches: [develop, main]

# Jobs
jobs:
  build-in-local: # job name
    runs-on: ubuntu-latest
    steps:
      # Before action : checkout source code
      - uses: actions/checkout@v2
      # Build using docker-compose file
      - name: Build the Docker images
        working-directory: ./deploy
        run: |
          docker-compose -f docker-compose-builder.yml build
