name: debate_publisher

# Trigger settings
on:
  # Depends on workflow
  workflow_run:
    # Details
    workflows: ["debate_image_pusher"]
    branches: [main]
    types:
      - completed

# Jobs
jobs:
  publish-to-oci: # job name
    runs-on: ubuntu-latest
    steps:
      # Before action : checkout source code
      - uses: actions/checkout@v2
      # 1. Write settings for OCI
      - name: "Write Config(For OCI)"
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
      # 2. Install OCI client
      - name: "Install OCI CLI"
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL
      # 3. Execute OCI client for changing config files
      - name: "Fix Config File Permissions"
        run: |
          oci setup repair-file-permissions --file /home/runner/.oci/config
          oci setup repair-file-permissions --file /home/runner/.oci/key.pem
      # 4. Get Instance public IP
      - name: "Get Instance IP"
        run: |
          echo "INSTANCE_IP=$( \
            oci compute instance list-vnics \
            --instance-id ${{secrets.INSTANCE_OCID}} \
            --query 'data [0]."public-ip"' \
            --raw-output \
          )" >> $GITHUB_ENV
      # 5. Preparing ssh (Try to connect SSH)
      - name: "Wait for SSH"
        run: |
          while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
                  sleep 5
                  echo "SSH not available..."
          done; echo "SSH ready!"
      # 6. Upload docker-compose file for running app using scp-action
      - name: "Push docker-compose file for running"
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          source: "deploy/docker-compose-runner.yml"
          target: "debate_app"
      # 7. Pull latest images
      - name: "Pull Images"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            sudo docker-compose -f debate_app/deploy/docker-compose-runner.yml pull
      # 8. Start container
      - name: "Restart App (only frontend, backend)"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            sudo docker-compose -f debate_app/deploy/docker-compose-runner.yml up -d --no-deps frontend backend
